### PR TITLE
Issue/44/dht11/22

### PR DESCRIPTION
**Pull request by raintonr**

### CODE REVIEW

**Comment by raintonr** [comment]
This is quite a few changes, so if you would be so kind as to look over this @Apollon77. Thx :)

**Comment by Apollon77** [comment]
Puuhhh ... honestly ... a real review would need to go into the full logic ... I can not provide that at the moment ... sorry
I will do a semantic review

**Comment by raintonr** [comment]
Yeah, whatever you can do. Been running without issue in our garage for a while now and no issues found so probably good to go :)

**Comment by Apollon77** [comment]
Ok, I mergeit now ... should we then release an official update? Minor or major (is ot breaking/renaming anything)?

**Comment by raintonr** [comment]
> Ok, I mergeit now ... should we then release an official update? Minor or major (is ot breaking/renaming anything)?

Sure, that's what #49 is there for. I'll create another PR after I update the files.

There shouldn't be anything that breaks - we discussed making this 1.3.0: https://github.com/iobroker-community-adapters/ioBroker.rpi2/issues/49#issuecomment-739709777

**Pull request merged**
